language: en

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
#- name: "CountVectorsFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "EmbeddingIntentClassifier"
- name: DucklingHTTPExtractor
  url: http://duckling:8000
  dimensions:
  - email
  - email_addr
  - duration
  - time
policies:
- name: AugmentedMemoizationPolicy
- name: EmbeddingPolicy
  max_history: 2
  batch_strategy: sequence
  epochs: 100
  evaluate_on_num_examples: 0
- name: FormPolicy
