# .env
# RASA_X_VERSION=0.23.5
# RASA_SDK_VERSION=1.5.1
# docker-compose build
# docker-compose up -d
version: "3.4"

services:
  rasa-x:
    #image: rasax:${RASA_X_VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - RASA_X_VERSION
        - RASA_X_PASSWORD=xyzzy
    environment:
      - RASA_HOME=/app
    ports:
      - "5005:5005"
      - "5002:5002"
    volumes:
      - ./:/app
    command: rasa x --no-prompt --endpoints endpoints.yml --credentials credentials-local.yml --port 5005 --cors "*" --debug
#    command: /app/rasax.sh
  app:
    image: rasa/rasa-sdk:${RASA_SDK_VERSION}
    #build:
    #  context: ./actions
    #  dockerfile: ./actions/Dockerfile
    #  args:
    #    - RASA_SDK_VERSION
    volumes:
      - "./actions:/app/actions"
    ports:
      - "5055:5055"
