name: Build Action Image
#on: [push]
on:
  workflow_dispatch:
      why:
        description: 'Why are you running'
        required: false
        default: 'Testing Workflow'
      image-tag:
        description: 'What image tag do you want to use?'
        required: true
        default: 'latest'
      sdk-vers:
        description: 'Rasa SDK version?'
        required: true
        default: '2.7.0'
  pull_request:
#  push:
#    paths:
#    - 'actions/**'
#    - '.github/workflows/build-action-image.yml'

jobs:
  lint-testing:
    name: Code Formatting Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade "pip<20"
        pip install -r requirements-dev.txt
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint

  type-testing:
    name: Type Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Type Checking
      working-directory: ${{ github.workspace }}
      run: |
        make types

  build-image:
    name: Build Action Server Docker Image
    runs-on: ubuntu-latest
    needs: [lint-testing,type-testing]

    env:
      RASA_SDK_VERS: 2.7.0
      DOCKER_IMAGE_TAG: ${{ github.event.inputs.image-tag }}
      DOCKERHUB_USERNAME: stephens
      DOCKER_IMAGE_NAME: stephens/jokebot
      REQUIREMENTS_FILE: 'actions/requirements.txt'

    steps:
      - name: Checkout git repository ðŸ•
        uses: actions/checkout@v2
      - name: Build Actions Server Image
        uses: RasaHQ/rasa-action-server-gha@main
        with:
          actions_directory: 'actions'
          requirements_file: ${{ env.REQUIREMENTS_FILE }}
          docker_registry_login: ${{ env.DOCKERHUB_USERNAME }}
          docker_registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}
          docker_image_tag: ${{ env.DOCKER_IMAGE_TAG }}
          rasa_sdk_version: ${{ env.RASA_SDK_VERS }}

  manual-build-image:
    name: Build Action Server Docker Image
    if: ${{ github.event.inputs.why }}
    runs-on: ubuntu-latest

    env:
      RASA_SDK_VERS: ${{ github.event.inputs.sdk-version }}
      DOCKER_IMAGE_TAG: ${{ github.event.inputs.image-tag }}
      DOCKERHUB_USERNAME: stephens
      DOCKER_IMAGE_NAME: stephens/jokebot
      REQUIREMENTS_FILE: 'actions/requirements.txt'

    steps:
      - name: Checkout git repository ðŸ•
        uses: actions/checkout@v2
      - name: Build Actions Server Image
        uses: RasaHQ/rasa-action-server-gha@master
        with:
          actions_directory: 'actions'
          requirements_file: ${{ env.REQUIREMENTS_FILE }}
          docker_registry_login: ${{ env.DOCKERHUB_USERNAME }}
          docker_registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}
          docker_image_tag: ${{ env.DOCKER_IMAGE_TAG }}
          rasa_sdk_version: ${{ env.RASA_SDK_VERS }}